baseURL = 'https://jaiming724.github.io/blog/'
languageCode = 'en-us'
title = 'My New Blog'
theme = 'poison'
[pagination]
  pagerSize = 10

[params]
  brand = "My Blog"
  color = "blue"                 # Options: red, orange, yellow, green, teal, blue, purple, pink
  mode = "toggle"                # Options: auto, dark, light, toggle
  description = "A minimalist blog."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 2
  [[menu.main]]
    name = "Lifestyle"
    url = "/lifestyle/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 5
