baseURL = 'https://jaiming724.github.io/blog/'
languageCode = 'en-us'
title = 'My New Blog'
theme = 'poison'
[pagination]
  pagerSize = 10

[params]
  brand = "My Blog"
  color = "blue"                 # Options: red, orange, yellow, green, teal, blue, purple, pink
  mode = "toggle"                # Options: auto, dark, light, toggle
  description = "A minimalist blog."

[taxonomies]
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/topics/"
    weight = 2
